### ISSUE TITLE
Critical: Needs more jQuery

### ISSUE THREAD

**Issue by turbo** [ConorOBrien-Foxx/PPCG-Chat-Bot#1]
There is a disappointing lack of jQuery in your code. This could brake compatibility with stubborn sackoverflow users.

**Comment by red-green** [comment]
JQUERY IS LIFE

**Comment by ConorOBrien-Foxx** [comment]
jQuery is for skrubs.

**Comment by vampjaz** [comment]
> sackoverflow

Do you come from a farming site? Too many potato?

**Comment by ConorOBrien-Foxx** [comment]
Imported jQuery using ubiquitous `import` syntax.

**Comment by turbo** [comment]
\o/
